const CARDS = [
  { word: "benchmark", example: "We benchmarked our pricing against three major competitors.", zh: "基準評估", translation: "我們拿三家主要競爭對手來做價格基準比較。", category: "策略" },
  { word: "allocate", example: "We need to allocate more budget to customer acquisition.", zh: "分配資源", translation: "我們需要把更多預算分配到客戶獲取上。", category: "營運" },
  { word: "leverage", example: "We should leverage our existing network to enter the market faster.", zh: "善用", translation: "我們應該善用既有人脈網絡，更快打入市場。", category: "策略" },
  { word: "alignment", example: "We need better alignment between product and sales.", zh: "對齊，一致性", translation: "我們需要讓產品部門與業務部門有更好的對齊。", category: "管理" },
  { word: "feasibility", example: "Let's assess the feasibility of launching in Q3.", zh: "可行性", translation: "我們來評估第三季推出的可行性。", category: "專案" },
  { word: "mitigate", example: "We need a plan to mitigate supply chain risks.", zh: "降低風險，緩解", translation: "我們需要一套方案來降低供應鏈風險。", category: "風險" },
  { word: "streamline", example: "The new tool will streamline our approval process.", zh: "簡化流程", translation: "這個新工具會簡化我們的核准流程。", category: "營運" },
  { word: "differentiate", example: "We need to differentiate our service from lower-cost competitors.", zh: "差異化", translation: "我們需要讓服務與低價競爭者做出差異化。", category: "行銷" },
  { word: "compliance", example: "All marketing materials must meet compliance requirements.", zh: "合規", translation: "所有行銷素材都必須符合合規要求。", category: "法務" },
  { word: "retention", example: "Customer retention is more profitable than constant acquisition.", zh: "留存", translation: "客戶留存比持續拉新更有利潤。", category: "行銷" },
  { word: "forecast", example: "The sales forecast needs to be updated weekly.", zh: "預測", translation: "銷售預測需要每週更新。", category: "財務" },
  { word: "profitability", example: "The board is focused on long-term profitability.", zh: "獲利能力", translation: "董事會關注的是長期獲利能力。", category: "財務" },
  { word: "roadmap", example: "The product roadmap will be reviewed next month.", zh: "路線圖", translation: "產品路線圖將在下個月檢討。", category: "產品" },
  { word: "scalability", example: "We must ensure the platform has enough scalability.", zh: "可擴展性", translation: "我們必須確保平台有足夠的可擴展性。", category: "產品" },
  { word: "positioning", example: "Our positioning should emphasize premium service.", zh: "市場定位", translation: "我們的市場定位應該強調高階服務。", category: "行銷" },
  { word: "stakeholder", example: "We need stakeholder approval before moving forward.", zh: "利害關係人", translation: "在繼續之前，我們需要利害關係人核准。", category: "管理" },
  { word: "timeline", example: "Can you confirm the revised timeline?", zh: "時程", translation: "你可以確認修訂後的時程嗎？", category: "專案" },
  { word: "deliverable", example: "The final deliverable is due at the end of the month.", zh: "交付成果", translation: "最終交付成果在月底到期。", category: "專案" },
  { word: "touch base", example: "Let's touch base tomorrow morning.", zh: "簡短對一下", translation: "我們明天早上簡短對一下。", category: "溝通" },
  { word: "walk through", example: "Can you walk us through the proposal?", zh: "逐步說明", translation: "你可以逐步帶我們看這份提案嗎？", category: "溝通" },
  { word: "agenda", example: "I've shared the agenda for tomorrow's meeting.", zh: "議程", translation: "我已經分享明天會議的議程。", category: "溝通" },
  { word: "follow-up", example: "I'll send a follow-up email after the call.", zh: "後續追蹤", translation: "通話後我會寄一封後續追蹤信。", category: "溝通" },
  { word: "recap", example: "Could you recap the key decisions before we close?", zh: "重點回顧", translation: "結束前你可以回顧一下關鍵決策嗎？", category: "溝通" },
  { word: "clarify", example: "I want to clarify the expected timeline.", zh: "釐清", translation: "我想釐清預期的時程。", category: "溝通" },
  { word: "confirm", example: "Please confirm whether the shipment left on time.", zh: "確認", translation: "請確認貨物是否準時出貨。", category: "溝通" },
  { word: "propose", example: "I'd like to propose a simpler pricing model.", zh: "提議", translation: "我想提議一個更簡單的定價模式。", category: "溝通" },
  { word: "negotiate", example: "We are negotiating better payment terms with the vendor.", zh: "協商", translation: "我們正在和供應商協商更好的付款條件。", category: "談判" },
  { word: "deadline", example: "The deadline has been moved to next Friday.", zh: "截止期限", translation: "截止期限已經延到下週五。", category: "專案" },
  { word: "milestone", example: "Reaching this milestone will unlock the next phase.", zh: "里程碑", translation: "達成這個里程碑後就能進入下一階段。", category: "專案" },
  { word: "dependency", example: "This task has a dependency on the finance team's approval.", zh: "相依項目", translation: "這項任務依賴財務團隊的核准。", category: "專案" },
  { word: "scope", example: "We need to define the project scope more clearly.", zh: "範圍", translation: "我們需要更清楚界定專案範圍。", category: "專案" },
  { word: "priority", example: "Customer issues remain our top priority this quarter.", zh: "優先順序", translation: "客戶問題仍是我們本季的最高優先事項。", category: "管理" },
  { word: "ownership", example: "Each deliverable needs a clear owner and timeline.", zh: "負責歸屬", translation: "每項交付成果都需要明確的負責人和時程。", category: "管理" },
  { word: "escalation", example: "If the issue continues, we may need an escalation path.", zh: "升級處理", translation: "如果問題持續，我們可能需要升級處理機制。", category: "管理" },
  { word: "approval", example: "The campaign is pending final approval from legal.", zh: "核准", translation: "這個活動還在等法務做最終核准。", category: "管理" },
  { word: "execution", example: "A good strategy means nothing without strong execution.", zh: "執行", translation: "沒有強而有力的執行，再好的策略也沒有意義。", category: "營運" },
  { word: "implementation", example: "System implementation will start after user training.", zh: "導入執行", translation: "系統導入會在使用者訓練之後開始。", category: "專案" },
  { word: "rollout", example: "The software rollout will happen in three stages.", zh: "分階段推出", translation: "這套軟體會分三個階段推出。", category: "產品" },
  { word: "launch", example: "We plan to launch the new service in early June.", zh: "推出", translation: "我們計畫在六月初推出新服務。", category: "產品" },
  { word: "backlog", example: "The backlog includes several high-impact requests.", zh: "待辦清單", translation: "待辦清單裡有幾項高影響力需求。", category: "產品" },
  { word: "requirement", example: "Let's review the business requirements before development starts.", zh: "需求", translation: "開發開始前，我們先檢查商業需求。", category: "產品" },
  { word: "feature", example: "This feature was designed to reduce manual work.", zh: "功能", translation: "這個功能是為了減少人工操作而設計的。", category: "產品" },
  { word: "iterate", example: "We can iterate on the design after the first round of feedback.", zh: "迭代優化", translation: "收到第一輪回饋後，我們可以再迭代優化設計。", category: "產品" },
  { word: "optimize", example: "We need to optimize our checkout flow for mobile users.", zh: "最佳化", translation: "我們需要最佳化行動用戶的結帳流程。", category: "營運" },
  { word: "efficiency", example: "Automation improved the team's efficiency significantly.", zh: "效率", translation: "自動化大幅提升了團隊效率。", category: "營運" },
  { word: "productivity", example: "The new dashboard boosted sales productivity.", zh: "生產力", translation: "新的儀表板提升了業務團隊的生產力。", category: "營運" },
  { word: "bottleneck", example: "Manual review is the main bottleneck in the process.", zh: "瓶頸", translation: "人工審核是這個流程的主要瓶頸。", category: "營運" },
  { word: "workflow", example: "We redesigned the workflow to reduce handoff delays.", zh: "工作流程", translation: "我們重新設計了工作流程，以減少交接延遲。", category: "營運" },
  { word: "turnaround", example: "Our turnaround time for support tickets has improved.", zh: "處理周轉時間", translation: "我們處理客服單的周轉時間已經改善。", category: "營運" },
  { word: "procurement", example: "Procurement is reviewing the hardware purchase request.", zh: "採購", translation: "採購部正在審查硬體採買申請。", category: "採購" },
  { word: "inventory", example: "We need more accurate inventory data before the promotion.", zh: "庫存", translation: "促銷開始前，我們需要更精準的庫存資料。", category: "供應鏈" },
  { word: "fulfillment", example: "Order fulfillment slowed down during the holiday season.", zh: "履約出貨", translation: "假期期間的訂單履約出貨速度變慢了。", category: "供應鏈" },
  { word: "logistics", example: "Rising logistics costs are affecting our margins.", zh: "物流", translation: "物流成本上升正在影響我們的利潤。", category: "供應鏈" },
  { word: "vendor", example: "We are evaluating a new vendor for cloud services.", zh: "供應商", translation: "我們正在評估新的雲端服務供應商。", category: "採購" },
  { word: "quotation", example: "Please send the updated quotation by end of day.", zh: "報價單", translation: "請在今天下班前寄出更新後的報價單。", category: "採購" },
  { word: "invoice", example: "The invoice should match the approved purchase order.", zh: "發票", translation: "發票內容應該和核准的採購單一致。", category: "財務" },
  { word: "budget", example: "We need to stay within the approved budget.", zh: "預算", translation: "我們需要控制在核准的預算內。", category: "財務" },
  { word: "revenue", example: "Recurring revenue grew by 18 percent this year.", zh: "營收", translation: "經常性營收今年成長了百分之十八。", category: "財務" },
  { word: "margin", example: "Discounting too heavily will hurt our margin.", zh: "利潤率", translation: "折扣打太重會傷害我們的利潤率。", category: "財務" },
  { word: "expense", example: "Travel expenses must be submitted within five days.", zh: "費用", translation: "差旅費必須在五天內申報。", category: "財務" },
  { word: "overhead", example: "We should cut overhead before expanding headcount.", zh: "間接成本", translation: "在擴編之前，我們應該先降低間接成本。", category: "財務" },
  { word: "cash flow", example: "Cash flow is tight, so let's delay nonessential spending.", zh: "現金流", translation: "現金流偏緊，所以先延後非必要支出。", category: "財務" },
  { word: "break-even", example: "The new branch is expected to break even within a year.", zh: "損益兩平", translation: "新分店預計在一年內達到損益兩平。", category: "財務" },
  { word: "audit", example: "The internal audit will start next Monday.", zh: "稽核", translation: "內部稽核將在下週一開始。", category: "法務" },
  { word: "policy", example: "Please review the updated remote work policy.", zh: "政策", translation: "請檢查更新後的遠距工作政策。", category: "法務" },
  { word: "contract", example: "The contract needs one more legal review before signing.", zh: "合約", translation: "這份合約簽署前還需要一次法務審查。", category: "法務" },
  { word: "clause", example: "There's a termination clause on page four.", zh: "條款", translation: "第四頁有一條終止條款。", category: "法務" },
  { word: "liability", example: "We need to limit our liability in the agreement.", zh: "法律責任", translation: "我們需要在協議中限制自身法律責任。", category: "法務" },
  { word: "confidentiality", example: "Confidentiality is critical during the acquisition process.", zh: "保密性", translation: "在併購過程中，保密性非常關鍵。", category: "法務" },
  { word: "onboarding", example: "The new onboarding program shortens time to productivity.", zh: "新人到職導入", translation: "新的到職導入計畫縮短了新人進入狀況的時間。", category: "人資" },
  { word: "attrition", example: "Attrition has increased in the customer support team.", zh: "人員流失", translation: "客服團隊的人員流失率上升了。", category: "人資" },
  { word: "headcount", example: "We don't have headcount approval for another hire yet.", zh: "編制人數", translation: "我們目前還沒有新增招募名額的核准。", category: "人資" },
  { word: "hiring", example: "Hiring for the regional manager role starts this month.", zh: "招募", translation: "區域經理職缺的招募將在本月開始。", category: "人資" },
  { word: "training", example: "Sales training will focus on objection handling.", zh: "訓練", translation: "業務訓練將聚焦在異議處理。", category: "人資" },
  { word: "performance", example: "We review performance twice a year.", zh: "績效表現", translation: "我們一年做兩次績效評估。", category: "人資" },
  { word: "engagement", example: "Employee engagement improved after the policy changes.", zh: "投入度", translation: "政策調整後，員工投入度提高了。", category: "人資" },
  { word: "incentive", example: "The incentive plan is tied to quarterly results.", zh: "獎勵機制", translation: "這套獎勵制度和季度成果掛鉤。", category: "人資" },
  { word: "conversion", example: "Our landing page conversion rate is below target.", zh: "轉換", translation: "我們登陸頁的轉換率低於目標。", category: "行銷" },
  { word: "pipeline", example: "The sales pipeline looks healthy for next quarter.", zh: "銷售管線", translation: "下季的銷售管線看起來很健康。", category: "銷售" },
  { word: "lead", example: "The webinar generated 200 qualified leads.", zh: "潛在客戶名單", translation: "這場線上研討會帶來了兩百筆合格潛在客戶。", category: "行銷" },
  { word: "prospect", example: "The prospect asked for a product demo next week.", zh: "潛在客戶", translation: "這位潛在客戶要求下週看產品展示。", category: "銷售" },
  { word: "account", example: "This account has strong growth potential in Asia.", zh: "客戶帳戶", translation: "這個客戶在亞洲市場有很大的成長潛力。", category: "銷售" },
  { word: "upsell", example: "Customer success identified an upsell opportunity.", zh: "向上銷售", translation: "客戶成功團隊發現了一個向上銷售機會。", category: "銷售" },
  { word: "cross-sell", example: "We can cross-sell premium support to enterprise clients.", zh: "交叉銷售", translation: "我們可以向企業客戶交叉銷售高級支援服務。", category: "銷售" },
  { word: "churn", example: "High churn is a warning sign for product fit.", zh: "流失率", translation: "高流失率是產品契合度不足的警訊。", category: "行銷" },
  { word: "campaign", example: "The holiday campaign exceeded all engagement targets.", zh: "行銷活動", translation: "這次假期行銷活動超過了所有互動目標。", category: "行銷" },
  { word: "outreach", example: "Our outreach strategy needs to feel more personalized.", zh: "主動接觸開發", translation: "我們的主動開發策略需要更有個人化。", category: "行銷" },
  { word: "brand equity", example: "Consistent messaging helps build brand equity over time.", zh: "品牌資產", translation: "一致的訊息傳遞有助於長期累積品牌資產。", category: "行銷" },
  { word: "value proposition", example: "Our value proposition must be clear on the homepage.", zh: "價值主張", translation: "我們的價值主張必須在首頁清楚呈現。", category: "行銷" },
  { word: "competitive advantage", example: "Speed of execution is one of our main competitive advantages.", zh: "競爭優勢", translation: "執行速度是我們的主要競爭優勢之一。", category: "策略" },
  { word: "market share", example: "We gained market share in the mid-sized business segment.", zh: "市場占有率", translation: "我們在中型企業市場提升了市占率。", category: "策略" },
  { word: "expansion", example: "Regional expansion will depend on local partnerships.", zh: "擴張", translation: "區域擴張將取決於當地合作夥伴。", category: "策略" },
  { word: "synergy", example: "The merger should create synergies across both teams.", zh: "綜效", translation: "這次合併應該能為兩個團隊帶來綜效。", category: "策略" },
  { word: "contingency", example: "We need a contingency plan in case demand drops suddenly.", zh: "備援方案", translation: "如果需求突然下滑，我們需要一套備援方案。", category: "風險" },
  { word: "exposure", example: "Our currency exposure has increased this quarter.", zh: "風險曝險", translation: "我們本季的匯率曝險提高了。", category: "風險" },
  { word: "due diligence", example: "The investors are still conducting due diligence.", zh: "盡職調查", translation: "投資人仍在進行盡職調查。", category: "風險" },
  { word: "incident", example: "We documented the incident and reviewed the response time.", zh: "事件", translation: "我們已記錄這起事件並檢討回應時間。", category: "風險" },
  { word: "root cause", example: "The team is investigating the root cause of the outage.", zh: "根本原因", translation: "團隊正在調查這次中斷的根本原因。", category: "風險" },
  { word: "accountability", example: "Clear accountability prevents tasks from being overlooked.", zh: "問責歸屬", translation: "明確的問責歸屬能避免任務被忽略。", category: "管理" },
  { word: "consensus", example: "We need consensus before changing the pricing structure.", zh: "共識", translation: "調整定價結構前，我們需要先取得共識。", category: "管理" }
];
